### ISSUE TITLE
pm2.json

### ISSUE THREAD

**Issue by bpurdyiv** [ne1ro/capistrano_pm2#1]
Getting an error: no such file or directory 'config/pm2.json'

How is this file created, what is it supposed to contain?

Thanks!

**Comment by ne1ro** [comment]
It`s PM2 configuration file: http://pm2.keymetrics.io/docs/usage/application-declaration/
You can manually create it or generate.

**Comment by bpurdyiv** [comment]
Awesome! Thank you
