### ISSUE TITLE
Symlink issue

### ISSUE THREAD

**Issue by maxmumford** [ne1ro/capistrano_pm2#2]
Hey, my Capistrano build deploys the latest version by symlinking the "current" directory to the latest release. When pm2 is started, the script path is set to the _resolved_ path, not the symlink, ie:

/home/deploy/www/project/releases/20160622124329/app.js

when it should be:

/home/deploy/www/project/releases/current/app.js

This means that when you deploy a new version the old version is still served even after a pm2 restart. Any idea how to fix this?

**Comment by maxmumford** [comment]
As a workaround I delete the pm2 app then recreate it with the following task:

```
namespace :pm2 do

  desc 'Recreate pm2 app'
  task :recreate do
    on roles(:app) do
      within release_path do
        execute :pm2, 'delete', fetch(:pm2_app_name)
        execute :pm2, 'start', fetch(:pm2_config)
      end
    end
  end

end
```

With the following variables set:

```
set :pm2_config, ->{ "#{fetch(:deploy_to)}/current/config/pm2.json" }
set :pm2_app_name, 'property-investment-calculator'
```

Note that the pm2_app_name should be the same as in your config/pm2.json file.

There must be a better way around this though?

Thanks

**Comment by ne1ro** [comment]
Hi @maxmumford

> This means that when you deploy a new version the old version is still served even after a pm2 restart. Any idea how to fix this?

I think in that case pm2 should restart on `deploy:updated` hook within _release_ , not _current_ path. I'll try to check this later.

> Note that the pm2_app_name should be the same as in your config/pm2.json file.
> There must be a better way around this though?

Yes, you can set as `pm2_config` name of your application and it should work:

```
set :pm2_conf, 'myapp'
execute :pm2, 'start', fetch(:pm2_config) # pm2 start myapp

```

**Comment by ajimix** [comment]
I had the same issue. Changing to the config proposed by @maxmumford worked for me.

Thanks!

**Comment by maxmumford** [comment]
Hi @ne1ro, thanks for your help. Because my workaround solved the problem too, I probably won't find time to revisit this issue, so I'll close it. Thanks again
